spring:
  datasource:
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: 123456
      connection-init-sql: SET NAMES utf8mb4 COLLATE utf8mb4_unicode_ci
      read-only: false
      maximum-pool-size: 100
      minimum-idle: 10
    url: jdbc:mysql://localhost:3306/baomidou?serverTimezone=UTC