# spring.cloud.stream.bindings.[output].destination:         交换机的名称
# spring.cloud.stream.bindings.[output].group:               组，用于生成队列，组名相同时可以实现分布式
# spring.cloud.stream.bindings.[input].destination:          交换机的名称
# spring.cloud.stream.bindings.[input].group:                组，用于生成队列，组名相同时可以实现分布式
# spring.cloud.stream.bindings.[input].consumer.concurrency: 消费者的并发量
# spring.rabbitmq.addresses:                                 服务器地址
# spring.rabbitmq.username:                                  账号
# spring.rabbitmq.password:                                  密码
# spring.rabbitmq.virtual-host:                              虚拟主机


spring:
  cloud:
    stream:
      bindings:
        output_channel:
          destination: exchange-3
          binder: rabbit_cluster
          group: queue-3
      binders:
        rabbit_cluster:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: 192.168.1.122
                port: 5672
                username: admin
                password: admin
                virtual-host: /
  application:
    name: producer
  rabbitmq:
    host: 192.168.1.122
    port: 5672
    username: admin
    password: admin
    virtual-host: /
server:
  port: 8001